### ISSUE TITLE
[Forge][3.7-1.20.1] Wrong translation keys in en_us file

### ISSUE THREAD

**Issue by Satrapie** [Hir0shiyt/RandomEnchants2#3]
Hello, I have a small bug to report :)

The translation keys for all five curse enchantments are incorrects

For example, for the Breaking curse

In the en_us.json file : 
`"curse.randomenchants2.breaking" : "Breaking Curse",`

Ingame  :
`enchantment.randomenchants2.breaking_curse`
![image](https://github.com/Hir0shiyt/RandomEnchantments2/assets/98442019/6508066b-987b-46b6-8300-317f0883590e)

**Comment by Hir0shiyt** [comment]
Makes sense since I put those in a different folder, give me some time and I'll fix it. Sorry for the inconvenience.

**Comment by Hir0shiyt** [comment]
Fixed in every version
